FROM rust:1-slim-bullseye AS chef
WORKDIR /app
RUN cargo install cargo-chef --locked


FROM chef AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json


FROM chef AS builder
COPY --from=planner /app/recipe.json recipe.json
RUN cargo chef cook --release --recipe-path recipe.json
COPY . .
RUN cargo update && cargo build --release


FROM debian:bullseye-slim AS prod
WORKDIR app
RUN apt-get update && rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/target/release/rustserver /app

#ARG SERVER_PORT
#ENV SERVER_PORT=$SERVER_PORT
#ARG DATABASE_URL
#ENV DATABASE_URL=$DATABASE_URL
#ARG DB_MAX_CONNECTIONS
#ENV DB_MAX_CONNECTIONS=$DB_MAX_CONNECTIONS

ENTRYPOINT ["/app/rustserver"]