FROM rust:1-slim-bullseye AS chef
WORKDIR /app
RUN cargo install cargo-chef --locked


FROM chef AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json


FROM chef AS builder
COPY --from=planner /app/recipe.json recipe.json
RUN cargo chef cook --release --recipe-path recipe.json
COPY . .
RUN cargo build --release


FROM debian:bullseye-slim AS prod
# Is workdir needed?
WORKDIR app
# I need the following to run the app.
RUN apt-get update \
    && apt-get install -y \
    git \
    grep \
    cloc \
    && rm -rf /var/lib/apt/lists/*

# Todo: Delete this when done.
COPY data/* /app/data/
COPY --from=builder /app/target/release/unsaferust /app

ARG SERVER_PORT
ENV SERVER_PORT=$SERVER_PORT
ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL
ARG DB_MAX_CONNECTIONS
ENV DB_MAX_CONNECTIONS=$DB_MAX_CONNECTIONS

ENTRYPOINT ["/app/unsaferust"]